import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import ClientSession from "@/components/ClientSession";
import ClientRecoil from "@/components/ClientRecoil";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className && "scrollbar-hide"}>
        <ClientSession>
          <ClientRecoil>
            <Header />
            <Modal />
            {children}
          </ClientRecoil>
        </ClientSession>
      </body>
    </html>
  );
}
